updateUserDetails:
      handler: lib/user.updateUserDetails
      description: update user details
      events:
        - http:
            path: updateUserDetails
            integration: lambda
            method: post
            cors: true
            request:
              passThrough: WHEN_NO_TEMPLATES
              template:
                  application/json: "{\"body\":$input.json('$')}"