updateOpeningHours:
      handler: lib/user.updateOpeningHours
      description: update opening hours of a business type account
      events:
        - http:
            path: updateOpeningHours
            integration: lambda
            method: post
            cors: true
            request:
              passThrough: WHEN_NO_TEMPLATES
              template:
                  application/json: "{\"body\":$input.json('$')}"