service: appointment

package:
  exclude:
    - src/**
    - tsconfig.json
    - __tests__/**
    - README.md
    - events

provider:
  name: aws
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, 'us-east-1'}:293458897566:table/Glow"

  runtime: nodejs8.10
  environment:
    REGION: ${opt:region, 'us-east-1'}
    STAGE: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 6
  region: ${opt:region, 'us-east-1'}

functions:
  - ${file(config/get-appointments.yml)}
  - ${file(config/cancel-appointment.yml)}
  - ${file(config/create-appointment.yml)}
  - ${file(config/get-appointments-by-client.yml)}
  - ${file(config/get-appointments-by-service-provider.yml)}
  - ${file(config/update-appointment-availability.yml)}
  - ${file(config/get-appointment-availability.yml)}
  - ${file(config/make-date-available.yml)}
  - ${file(config/update-appointment.yml)}

  