createPost:
      handler: lib/post.createPost
      description: create posts
      events:
        - http:
            path: createPost
            integration: lambda
            method: post
            cors: true
            request:
              passThrough: WHEN_NO_TEMPLATES
              template:
                  application/json: "{\"body\":$input.json('$')}"